baseURL = "http://rexs.tips/"
languageCode = "en-us"
title = "Rex's Tips"

# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# Author Info
[author]
  name = "Rex Walters"
  link = ""


[params]
  # LoveIt theme version
  version = "0.1.X"
  description = "Guitar, machining, metalworking, woodworking, games and computers"
  keywords=["Guitar", "Machining", "Metalworking", "Woodworking", "Luthery", "Go"]
  #[params.header]
  # Can't figure out what these do!
  #  # desktop header mode ("fixed", "normal", "auto")
  #  desktopMode = "normal"
  #  # mobile header mode ("fixed", "normal", "auto")
  #  mobileMode = "auto"
  [params.footer]
    # Site creation time
    since = 2019
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    # Home Page Info
  [params.home]
    # Home Page Profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "rex.home@gmail.com"
      # URL of avatar shown in home page
      avatarURL = "/img/rex-hs-small.jpg"
      # subtitle shown in home page
      subtitle = "Rex's tips: Learning, making, and just goofing around"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true

  [params.comment]
    enable = true
    # Disqus Comment Config (https://disqus.com/)
    [params.comment.disqus]
      # LoveIt   v0.1.1
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "rexstips"


[params.cdn]
  fontAwesomeFreeCSS = "https://kit.fontawesome.com/fe402a6cf8.js"

[menu]
  [[menu.main]]
    identifier = "all"
    pre = '<i class="fal fa-globe"></i>&nbsp;'
    name = "All"
    url = "/posts/"
    title = "All posts in any category"
    weight = 1
  [[menu.main]]
    identifier = "guitar"
    pre = "<i class='fal fa-guitars'></i>&nbsp;"
    name = "Guitar"
    url = "/categories/guitar/"
    title = "Guitar related topics"
    weight = 2
  [[menu.main]]
    identifier = "shop"
    pre = '<i class="far fa-hammer"></i>&nbsp;'
    name = "Shop"
    url = "/categories/shop/"
    title = "Shop stuff (metal/woodworking)"
    weight = 3
  [[menu.main]]
    identifier = "other"
    pre = '<i class="fal fa-ellipsis-h-alt"></i>&nbsp;'
    name = "Other"
    url = "/categories/other/"
    title = "Other categories"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    pre = '<i class="fal fa-tags"></i>'
    name = "Tags"
    url = "/tags/"
    title = "All posts sorted by tag"
    weight = 5
