[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. &&  npm install -D --save autoprefixer && npm install -D --save postcss-cli && hugo --gc --minify "
#command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.staging.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "staging"
HUGO_ENABLEGITINFO = "true"
