[build]
publish = "staging"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.staging.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "staging"
HUGO_ENABLEGITINFO = "true"
